<a href="https://colab.research.google.com/github/liveleisurely/Curiosity/blob/main/Reinforcement_Learning_Frozen_Lake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gym
import numpy as np
import pickle
import time, os
from tqdm import tqdm

In [ ]:
env = gym.make('FrozenLake-v0', is_slippery=False)
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


Agent's four possible actions: left(0), down(1) right(2) up(3)

Reward : F=0, H=0, G=+1
States: S, H, F, G

\>> 4x4 = 16 states & 4 actions

In [ ]:
16*4 # dimension of Q-value function.

64

In [ ]:
total_episodes = 100000 ## number of episodes

lr_rate = 1 # the learning rate
gamma = 0.99 # the discount factor

## Q-table 16x4 matrix with zeros
Q = np.zeros((env.observation_space.n, env.action_space.n))

In [ ]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [ ]:
env.action_space.sample() # produce random action (0,1,2,3)

1

In [ ]:
env.step(2) # (index of the sell, reward, )

(1, 0.0, False, {'prob': 1.0})

In [ ]:
env.render()

  (Right)
SFFF
FHFH
FFFH
HFFG


In [ ]:
env.step(1)

(4, 0.0, False, {'prob': 1.0})

In [ ]:
env.render()

  (Down)
SFFF
FHFH
FFFH
HFFG


In [ ]:
env.step(1)

(8, 0.0, False, {'prob': 1.0})

In [ ]:
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [ ]:
env.step(2) # move to right

(1, 0.0, False, {'prob': 1.0})

In [ ]:
env.render() # real move

  (Right)
SFFF
FHFH
FFFH
HFFG


In [ ]:
env.step(2)

(5, 0, True, {'prob': 1.0})

In [ ]:
env.render()

  (Right)
SFFF
FHFH
FFFH
HFFG


In [ ]:
env.step(2)

(5, 0, True, {'prob': 1.0})

In [ ]:
env.render()

  (Down)
SFFF
FHFH
FFFH
HFFG


In [ ]:
epsilon = 0.5 ## the epsilon-greedy approach : epsilon-hyperparameter
def choose_action(state):
    if np.random.uniform(0,1) < epsilon:
        action = env.action_space.sample() # random actions
    else:
        action = np.argmax(Q[state, :])
    return action

## Using Q-Learning Algorithm, update Q-table
def learn(state, state2, reward, action):
    predict = Q[state, action]
    target = reward + gamma * np.max(Q[state2, :])
    Q[state, action] = Q[state, action] + lr_rate * (target - predict)

In [ ]:
for episode in tqdm(range(total_episodes)):
    state = env.reset()
    done = False
    
    while not done:
        action = choose_action(state)
        state2, reward, done, info = env.step(action) #  선택된 행동이 환경내에서 수행되고 다음 상태(state2)와 보상(reward) 반환, 에피소드가 끝났다면 done=True
        learn(state, state2, reward, action) ## Q-Learning Algorithm
        state = state2

print(Q)

with open("frozenLake_qTable.pkl", 'wb') as f:
    pickle.dump(Q, f)

100%|██████████| 100000/100000 [00:25<00:00, 3928.74it/s]

[[0.94148015 0.95099005 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.95099005 0.95099005]
 [0.95099005 0.96059601 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.96059601 0.         0.970299   0.95099005]
 [0.96059601 0.9801     0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.99       0.970299  ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [ ]:
Q # L,D,R,U 첫번째에서는 D 혹은 R을 선택할 것임

array([[0.94148015, 0.95099005, 0.95099005, 0.94148015],
       [0.94148015, 0.        , 0.96059601, 0.95099005],
       [0.95099005, 0.970299  , 0.95099005, 0.96059601],
       [0.96059601, 0.        , 0.95099005, 0.95099005],
       [0.95099005, 0.96059601, 0.        , 0.94148015],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.        , 0.96059601],
       [0.        , 0.        , 0.        , 0.        ],
       [0.96059601, 0.        , 0.970299  , 0.95099005],
       [0.96059601, 0.9801    , 0.9801    , 0.        ],
       [0.970299  , 0.99      , 0.        , 0.970299  ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.9801    , 0.99      , 0.970299  ],
       [0.9801    , 0.99      , 1.        , 0.9801    ],
       [0.        , 0.        , 0.        , 0.        ]])

In [ ]:
after updating Q-value function, agents can play the game automatically based on Q-value

In [ ]:
import gym
import numpy as np
import pickle
import time, os

env = gym.make('FrozenLake-v0', is_slippery=False)

with open("frozenLake_qTable.pkl", 'rb') as f:
    Q = pickle.load(f)

def choose_action(state):
    action = np.argmax(Q[state, :])
    return action

# start
for episode in range(5):
    state = env.reset()
    print("*** Episode: ", episode)
    t = 0
    while t < 100:
        env.render()
        action = choose_action(state)
        state2, reward, done, info = env.step(action)
        state = state2
        if done:
            break
        
        time.sleep(0.5)
        os.system('clear')

*** Episode:  0

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
*** Episode:  1

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
*** Episode:  2

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
*** Episode:  3

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
*** Episode:  4

SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
